# Generated by Django 6.0.4 on 2026-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('viewer', 'Viewer'), ('creator', 'Creator'), ('admin', 'Admin')], default='viewer', max_length=10, null=True),
        ),
    ]
