# Generated by Django 6.0.4 on 2026-04-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
