# Generated by Django 6.0.4 on 2026-04-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_rename_thumbnail_episode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
