# Generated by Django 6.0.4 on 2026-06-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_alter_episode_id_alter_film_id_alter_pub_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='compression_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminée'), ('error', 'Erreur')], default='pending', max_length=20),
        ),
    ]
