# Generated by Django 6.0.4 on 2026-06-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_add_compression_status_to_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['nom']},
        ),
    ]
