# Generated by Django 6.0.4 on 2026-06-26 11:09

import root.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_alter_episode_description_alter_film_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=root.utils.upload_to('episodes/images')),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(upload_to=root.utils.upload_to('images')),
        ),
        migrations.AlterField(
            model_name='pub',
            name='image',
            field=models.ImageField(upload_to=root.utils.upload_to('pubs/images')),
        ),
        migrations.AlterField(
            model_name='pub',
            name='video',
            field=models.FileField(upload_to=root.utils.upload_to('pubs/videos')),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=root.utils.upload_to('videos')),
        ),
    ]
